# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Chart": "chart.ipynb",
         "BasePlot": "chart_base_plot.ipynb",
         "default_palette": "chart_color.ipynb",
         "color_types": "chart_color.ipynb",
         "palette_contrast2": "chart_color.ipynb",
         "palette_compare3": "chart_color.ipynb",
         "construct_categorical_data": "chart_data_model.ipynb",
         "PlotBar": "chart_plot_bar.ipynb",
         "Style": "chart_style.ipynb",
         "cast_date": "data_processing_time_series.ipynb",
         "count_time_value": "data_processing_time_series.ipynb",
         "time_over_time": "data_processing_time_series.ipynb",
         "dotdict": "utils_dotdict.ipynb"}

modules = ["chart/chart.py",
           "chart/base_plot.py",
           "chart/color.py",
           "chart/data_model.py",
           "chart/plot_bar.py",
           "chart/style.py",
           "data_processing/time_series.py",
           "util/dotdict.py"]

doc_url = "https://hirogen317.github.io/chamomile/"

git_url = "https://github.com/hirogen317/chamomile/tree/master/"

def custom_doc_links(name): return None
