# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_base_plot.ipynb (unless otherwise specified).

__all__ = ['BasePlot']

# Cell
from .chart import Chart
from bokeh.io import show

# Cell
class BasePlot():

    def __init__(self, chart=None, x_axis_type=None, y_axis_type=None):
        if chart is None:
            self._chart = Chart(x_axis_type=x_axis_type, y_axis_type=y_axis_type, plot_width=600, plot_height=400)

    def show(self):
        show(self._chart.figure)

    @property
    def chart(self):
        return self._chart
