# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_color.ipynb (unless otherwise specified).

__all__ = ['default_palette', 'color_types', 'palette_contrast2', 'palette_compare3']

# Cell
from ..util.dotdict import dotdict
from bokeh.palettes import Category20
from bokeh.transform import factor_cmap

# Cell
default_palette = Category20[20]
color_types = dotdict({'stress': default_palette[6], 'background': default_palette[14],
                       'first': default_palette[0], 'second': default_palette[2], 'third': default_palette[4]})
palette_contrast2 = [color_types.stress, color_types.background]
palette_compare3 = [color_types.first, color_types.second, color_types.stress]