# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_data_model.ipynb (unless otherwise specified).

__all__ = ['construct_categorical_data']

# Cell
import pandas as pd
from bokeh.models import ColumnDataSource

# Cell
def construct_categorical_data(data_frame: pd.DataFrame, c_col: str=None, v_col: str=None,
                               color_col: str=None, text_col: str=None):
    source = ColumnDataSource(data={
        'category': data_frame[c_col].values,
        'value': data_frame[v_col].values,
        'text': data_frame[text_col].values
    })

    return source
