# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_plot_scatter.ipynb (unless otherwise specified).

__all__ = ['PlotScatter']

# Cell
from .chart import Chart
from .data_model import construct_categorical_data
from .base_plot import BasePlot

import pandas as pd
from bokeh.io import output_notebook
import numpy as np

from bokeh.models.ranges import FactorRange, Range1d
from bokeh.io import show
output_notebook()

# Cell
class PlotScatter(BasePlot):
    def __init__(self, chart=None, x_axis_type='linear'):
        super().__init__(chart=chart, x_axis_type=x_axis_type)


    def scatter(self, df = None, x: str = None, y = None):
        p = self._chart.figure

        p.scatter(df[x], df[y], fill_color=self.next_color(), fill_alpha=0.6, line_color=None)

        return self
