# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_plot_bar.ipynb (unless otherwise specified).

__all__ = ['PlotBar']

# Cell
from .chart import Chart
from .data_model import construct_categorical_data
import pandas as pd
from bokeh.models.ranges import FactorRange, Range1d
from bokeh.io import show

# Cell
class PlotBar():

    def __init__(self, chart = None):
        x_axis_type = 'categorical'
        super().__init__(chart=chart, x_axis_type=None)


    def set_properties(**kwargs):
        if 'title' in kwargs:
            self._chart.set_title(kwargs['title'])
        return self

    def bar(self, data_frame: pd.DataFrame, category: str=None, value: float=None, text: str=None, color: str=None, title: str=None):
        source = construct_categorical_data(data_frame, c_col=category, v_col=value, text_col=text)
        print(source.data)
        p = self._chart.figure
        if title is not None:
            self._chart.set_title(title)

        p.x_range = FactorRange(factors=data_frame[category].values)
        print(data_frame[category].values)
        p.y_range = Range1d(0, data_frame[value].max() * 1.1)
        p.vbar(x='category', top='value', width=0.5, source=source)

        return self

    def bar_stacked(self, data_frame: pd.DataFrame, category: str=None, value: str=None,
                    stack: str=None, text: str=None, color: str=None, title: str=None):
        return self

    def bar_cascade(self, data_frame: pd.DataFrame):
        return self

    def bar_transition(self, data_frame: pd.DataFrame):
        return self

