# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_plot_bar.ipynb (unless otherwise specified).

__all__ = ['PlotBar']

# Cell
from .chart import Chart
from .data_model import construct_categorical_data
import pandas as pd
from bokeh.models.ranges import FactorRange, Range1d
from bokeh.io import show

# Cell
class PlotBar():

    def __init__(self, chart = None):
        if chart is None:
            self._chart = Chart(x_axis_type='categorical', plot_width=600, plot_height=400)

    @property
    def chart(self):
        return self._chart

    def set_properties(**kwargs):
        if 'title' in kwargs:
            self._chart.set_title(kwargs['title'])
        return self

    def bar(data_frame: pd.DataFrame, c_col: str=None, v_col: str=None, text_col: str=None, title: str=None):
        source = construct_categorical_data(data_frame, c_col=c_col, v_col=v_col, text_col=text_col)
        print(source.data)
        p = self.chart.figure
        if title is not None:
            chart.set_title(title)

        p.x_range = FactorRange(factors=data_frame[c_col].values)
        print(data_frame[c_col].values)
        p.y_range = Range1d(0, data_frame[v_col].max() * 1.1)
        p.vbar(x='category', top='value', width=0.5, source=source)

        return self

    def show():
        show(self._chart)