# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/chart_plot_bar.ipynb (unless otherwise specified).

__all__ = ['bar']

# Cell
from .chart import Chart
from .data_model import construct_categorical_data
import pandas as pd
from bokeh.models.ranges import FactorRange, Range1d
from bokeh.io import show

# Cell
def bar(data_frame: pd.DataFrame, c_col: str=None, v_col: str=None, text_col: str=None, title: str=None):
    source = construct_categorical_data(data_frame, c_col=c_col, v_col=v_col, text_col=text_col)
    chart = Chart(x_axis_type='categorical', plot_width=600, plot_height=400)
    print(source.data)

    if title is not None:
        chart.set_title(title)
    p = chart.figure
    p.x_range = FactorRange(factors=data_frame[c_col].values)
    print(data_frame[c_col].values)
    p.y_range = Range1d(0, data_frame[v_col].max() * 1.1)
    p.vbar(x='category', top='value', width=0.5, source=source)

    return chart.figure