# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/data_processing_numeric.ipynb (unless otherwise specified).

__all__ = ['moving_average']

# Cell
import pandas as pd

# Cell
def moving_average(data_frame: pd.DataFrame = None,
                          window: int=7,
                          group_col: str = None,
                          value_col: str = None,
                          shift=0)->pd.DataFrame:
    df = data_frame.copy()
    ma_col = '{value_col}_ma{window}'.format(value_col=value_col, window=window)
    if group_col is None:
        df[ma_col] = df[value_col].rolling(window=window).mean().shift(periods=shift)
    else:
        df[ma_col] = df.groupby(group_col)[value_col].apply(lambda x: x.rolling(window=window).mean().shift(periods=shift))
    return df[ma_col]